[package]
name = "trolleyman_org"
version = "0.1.0"
authors = ["Callum Tolley <cgtrolley@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["serve", "tera_templates"] }

rand = "0.7.3"
maplit = "1.0.2"
