
database_path = "data/db.sqlite3"
protocol = "http"
domain = "localhost:8000"

[recaptcha]
public_key = "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
private_key = "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"

[git-lfs]
path = "data/git-lfs"

[facebook-grpc]
host = "localhost:9001"
