version: "3.3"

services:
  rocket:
    build: .
    image: trolleyman.org:latest
    restart: always
    volumes:
      - "./data:/trolleyman.org/data"
      - "./logs:/trolleyman.org/logs"
    depends_on:
      - db

  caddy:
    image: abiosoft/caddy:latest
    restart: always
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./.caddy:/root/.caddy"
      - "./logs:/root/logs"
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_AGREE: "true"

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - "./database:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
