version: "3.3"

services:
  rocket:
    build: .
    image: trolleyman.org:latest
    restart: always
    volumes:
      - "./data:/trolleyman.org/data"
      - "./logs:/trolleyman.org/logs"

  caddy:
    image: abiosoft/caddy:latest
    restart: always
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./.caddy:/root/.caddy"
      - "./logs:/root/logs"
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_AGREE: "true"

  facebook_grpc:
    build: ./facebook_grpc
    image: facebook_grpc:latest
    restart: always
    volumes:
      - "./data:/app/data"
