version: "3.3"

services:
  rocket:
    build: .
    image: trolleyman.org:latest
    volumes:
      - "./database:/trolleyman.org/database"
      - "./scripts/restart_flag:/trolleyman.org/restart_flag"

  caddy:
    image: abiosoft/caddy:latest
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "./.caddy:/root/.caddy"
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_AGREE: true
