[package]
name = "trolleyman-org-xtask"
version = "0.1.0"
authors = ["Callum Tolley <cgtrolley@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
clap = "2.33.0"
structopt = "0.2.15"
wasm-pack = "0.8.1"
fs_extra = "1.1.0"
