# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import facebooksrv_pb2 as proto_dot_facebooksrv__pb2


class FacebookSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Login = channel.unary_unary(
        '/FacebookSrv/Login',
        request_serializer=proto_dot_facebooksrv__pb2.LoginDetails.SerializeToString,
        response_deserializer=proto_dot_facebooksrv__pb2.LoginToken.FromString,
        )


class FacebookSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FacebookSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=proto_dot_facebooksrv__pb2.LoginDetails.FromString,
          response_serializer=proto_dot_facebooksrv__pb2.LoginToken.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FacebookSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
