# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/facebook.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/facebook.proto',
  package='facebook',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14proto/facebook.proto\x12\x08\x66\x61\x63\x65\x62ook\"/\n\x0cLoginDetails\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"*\n\nLoginToken\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"E\n\nLoginError\x12&\n\x04kind\x18\x01 \x01(\x0e\x32\x18.facebook.LoginErrorKind\x12\x0f\n\x07message\x18\x02 \x01(\t\"e\n\x0bLoginResult\x12%\n\x05token\x18\x01 \x01(\x0b\x32\x14.facebook.LoginTokenH\x00\x12%\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.facebook.LoginErrorH\x00\x42\x08\n\x06result\"\x17\n\x04\x45\x63ho\x12\x0f\n\x07payload\x18\x01 \x01(\t*B\n\x0eLoginErrorKind\x12\x17\n\x13LOGIN_ERROR_UNKNOWN\x10\x00\x12\x17\n\x13LOGIN_ERROR_FB_CHAT\x10\x01\x32\xaa\x01\n\x08\x46\x61\x63\x65\x62ook\x12&\n\x04\x65\x63ho\x12\x0e.facebook.Echo\x1a\x0e.facebook.Echo\x12\x36\n\x05login\x12\x16.facebook.LoginDetails\x1a\x15.facebook.LoginResult\x12>\n\tlogin_all\x12\x16.facebook.LoginDetails\x1a\x15.facebook.LoginResult(\x01\x30\x01\x62\x06proto3'
)

_LOGINERRORKIND = _descriptor.EnumDescriptor(
  name='LoginErrorKind',
  full_name='facebook.LoginErrorKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOGIN_ERROR_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_ERROR_FB_CHAT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=326,
  serialized_end=392,
)
_sym_db.RegisterEnumDescriptor(_LOGINERRORKIND)

LoginErrorKind = enum_type_wrapper.EnumTypeWrapper(_LOGINERRORKIND)
LOGIN_ERROR_UNKNOWN = 0
LOGIN_ERROR_FB_CHAT = 1



_LOGINDETAILS = _descriptor.Descriptor(
  name='LoginDetails',
  full_name='facebook.LoginDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='facebook.LoginDetails.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='facebook.LoginDetails.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=81,
)


_LOGINTOKEN = _descriptor.Descriptor(
  name='LoginToken',
  full_name='facebook.LoginToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='facebook.LoginToken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='facebook.LoginToken.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=125,
)


_LOGINERROR = _descriptor.Descriptor(
  name='LoginError',
  full_name='facebook.LoginError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='facebook.LoginError.kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='facebook.LoginError.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=196,
)


_LOGINRESULT = _descriptor.Descriptor(
  name='LoginResult',
  full_name='facebook.LoginResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='facebook.LoginResult.token', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='facebook.LoginResult.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='facebook.LoginResult.result',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=198,
  serialized_end=299,
)


_ECHO = _descriptor.Descriptor(
  name='Echo',
  full_name='facebook.Echo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='facebook.Echo.payload', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=324,
)

_LOGINERROR.fields_by_name['kind'].enum_type = _LOGINERRORKIND
_LOGINRESULT.fields_by_name['token'].message_type = _LOGINTOKEN
_LOGINRESULT.fields_by_name['error'].message_type = _LOGINERROR
_LOGINRESULT.oneofs_by_name['result'].fields.append(
  _LOGINRESULT.fields_by_name['token'])
_LOGINRESULT.fields_by_name['token'].containing_oneof = _LOGINRESULT.oneofs_by_name['result']
_LOGINRESULT.oneofs_by_name['result'].fields.append(
  _LOGINRESULT.fields_by_name['error'])
_LOGINRESULT.fields_by_name['error'].containing_oneof = _LOGINRESULT.oneofs_by_name['result']
DESCRIPTOR.message_types_by_name['LoginDetails'] = _LOGINDETAILS
DESCRIPTOR.message_types_by_name['LoginToken'] = _LOGINTOKEN
DESCRIPTOR.message_types_by_name['LoginError'] = _LOGINERROR
DESCRIPTOR.message_types_by_name['LoginResult'] = _LOGINRESULT
DESCRIPTOR.message_types_by_name['Echo'] = _ECHO
DESCRIPTOR.enum_types_by_name['LoginErrorKind'] = _LOGINERRORKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginDetails = _reflection.GeneratedProtocolMessageType('LoginDetails', (_message.Message,), {
  'DESCRIPTOR' : _LOGINDETAILS,
  '__module__' : 'proto.facebook_pb2'
  # @@protoc_insertion_point(class_scope:facebook.LoginDetails)
  })
_sym_db.RegisterMessage(LoginDetails)

LoginToken = _reflection.GeneratedProtocolMessageType('LoginToken', (_message.Message,), {
  'DESCRIPTOR' : _LOGINTOKEN,
  '__module__' : 'proto.facebook_pb2'
  # @@protoc_insertion_point(class_scope:facebook.LoginToken)
  })
_sym_db.RegisterMessage(LoginToken)

LoginError = _reflection.GeneratedProtocolMessageType('LoginError', (_message.Message,), {
  'DESCRIPTOR' : _LOGINERROR,
  '__module__' : 'proto.facebook_pb2'
  # @@protoc_insertion_point(class_scope:facebook.LoginError)
  })
_sym_db.RegisterMessage(LoginError)

LoginResult = _reflection.GeneratedProtocolMessageType('LoginResult', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESULT,
  '__module__' : 'proto.facebook_pb2'
  # @@protoc_insertion_point(class_scope:facebook.LoginResult)
  })
_sym_db.RegisterMessage(LoginResult)

Echo = _reflection.GeneratedProtocolMessageType('Echo', (_message.Message,), {
  'DESCRIPTOR' : _ECHO,
  '__module__' : 'proto.facebook_pb2'
  # @@protoc_insertion_point(class_scope:facebook.Echo)
  })
_sym_db.RegisterMessage(Echo)



_FACEBOOK = _descriptor.ServiceDescriptor(
  name='Facebook',
  full_name='facebook.Facebook',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=395,
  serialized_end=565,
  methods=[
  _descriptor.MethodDescriptor(
    name='echo',
    full_name='facebook.Facebook.echo',
    index=0,
    containing_service=None,
    input_type=_ECHO,
    output_type=_ECHO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='login',
    full_name='facebook.Facebook.login',
    index=1,
    containing_service=None,
    input_type=_LOGINDETAILS,
    output_type=_LOGINRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='login_all',
    full_name='facebook.Facebook.login_all',
    index=2,
    containing_service=None,
    input_type=_LOGINDETAILS,
    output_type=_LOGINRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEBOOK)

DESCRIPTOR.services_by_name['Facebook'] = _FACEBOOK

# @@protoc_insertion_point(module_scope)
