# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import facebook_pb2 as proto_dot_facebook__pb2


class FacebookStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.login = channel.unary_unary(
        '/facebook.Facebook/login',
        request_serializer=proto_dot_facebook__pb2.LoginDetails.SerializeToString,
        response_deserializer=proto_dot_facebook__pb2.LoginToken.FromString,
        )
    self.echo = channel.unary_unary(
        '/facebook.Facebook/echo',
        request_serializer=proto_dot_facebook__pb2.Echo.SerializeToString,
        response_deserializer=proto_dot_facebook__pb2.Echo.FromString,
        )


class FacebookServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def echo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FacebookServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'login': grpc.unary_unary_rpc_method_handler(
          servicer.login,
          request_deserializer=proto_dot_facebook__pb2.LoginDetails.FromString,
          response_serializer=proto_dot_facebook__pb2.LoginToken.SerializeToString,
      ),
      'echo': grpc.unary_unary_rpc_method_handler(
          servicer.echo,
          request_deserializer=proto_dot_facebook__pb2.Echo.FromString,
          response_serializer=proto_dot_facebook__pb2.Echo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'facebook.Facebook', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
