# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/facebook.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/facebook.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14proto/facebook.proto\"/\n\x0cLoginDetails\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1b\n\nLoginToken\x12\r\n\x05token\x18\x01 \x01(\t22\n\x0b\x46\x61\x63\x65\x62ookSrv\x12#\n\x05login\x12\r.LoginDetails\x1a\x0b.LoginTokenb\x06proto3'
)




_LOGINDETAILS = _descriptor.Descriptor(
  name='LoginDetails',
  full_name='LoginDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='LoginDetails.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='LoginDetails.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=71,
)


_LOGINTOKEN = _descriptor.Descriptor(
  name='LoginToken',
  full_name='LoginToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='LoginToken.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['LoginDetails'] = _LOGINDETAILS
DESCRIPTOR.message_types_by_name['LoginToken'] = _LOGINTOKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoginDetails = _reflection.GeneratedProtocolMessageType('LoginDetails', (_message.Message,), {
  'DESCRIPTOR' : _LOGINDETAILS,
  '__module__' : 'proto.facebook_pb2'
  # @@protoc_insertion_point(class_scope:LoginDetails)
  })
_sym_db.RegisterMessage(LoginDetails)

LoginToken = _reflection.GeneratedProtocolMessageType('LoginToken', (_message.Message,), {
  'DESCRIPTOR' : _LOGINTOKEN,
  '__module__' : 'proto.facebook_pb2'
  # @@protoc_insertion_point(class_scope:LoginToken)
  })
_sym_db.RegisterMessage(LoginToken)



_FACEBOOKSRV = _descriptor.ServiceDescriptor(
  name='FacebookSrv',
  full_name='FacebookSrv',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=102,
  serialized_end=152,
  methods=[
  _descriptor.MethodDescriptor(
    name='login',
    full_name='FacebookSrv.login',
    index=0,
    containing_service=None,
    input_type=_LOGINDETAILS,
    output_type=_LOGINTOKEN,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEBOOKSRV)

DESCRIPTOR.services_by_name['FacebookSrv'] = _FACEBOOKSRV

# @@protoc_insertion_point(module_scope)
