table! {
    /// Representation of the `flappy_leaderboard` table.
    ///
    /// (Automatically generated by Diesel.)
    flappy_leaderboard (id) {
        /// The `id` column of the `flappy_leaderboard` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `flappy_leaderboard` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `score` column of the `flappy_leaderboard` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        score -> Integer,
        /// The `timestamp` column of the `flappy_leaderboard` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamp,
    }
}

table! {
    /// Representation of the `linc_interest` table.
    ///
    /// (Automatically generated by Diesel.)
    linc_interest (id) {
        /// The `id` column of the `linc_interest` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `linc_interest` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `desc` column of the `linc_interest` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        desc -> Text,
    }
}

table! {
    /// Representation of the `linc_person` table.
    ///
    /// (Automatically generated by Diesel.)
    linc_person (id) {
        /// The `id` column of the `linc_person` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `linc_person` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `interest1_id` column of the `linc_person` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        interest1_id -> Integer,
        /// The `interest2_id` column of the `linc_person` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        interest2_id -> Integer,
        /// The `interest3_id` column of the `linc_person` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        interest3_id -> Integer,
        /// The `twitter_pic_url` column of the `linc_person` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        twitter_pic_url -> Nullable<Text>,
        /// The `twitter` column of the `linc_person` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        twitter -> Nullable<Text>,
    }
}

allow_tables_to_appear_in_same_query!(
    flappy_leaderboard,
    linc_interest,
    linc_person,
);
