table! {
    /// Representation of the `flappy_leaderboard` table.
    ///
    /// (Automatically generated by Diesel.)
    flappy_leaderboard (id) {
        /// The `id` column of the `flappy_leaderboard` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `name` column of the `flappy_leaderboard` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `score` column of the `flappy_leaderboard` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        score -> Integer,
        /// The `timestamp` column of the `flappy_leaderboard` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        timestamp -> Timestamp,
    }
}
