# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlappyClone', '0002_auto_20170410_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
