# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlappyClone', '0003_auto_20170410_2319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserProfile',
        ),
    ]
