# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlappyClone', '0004_auto_20170410_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
